####################################################################################################
##    ▄▄▄   ▄▄▄·  ▐ ▄ ·▄▄▄▄        • ▌ ▄ ·.     ▄▄▄▄▄▄▄▄ .▄▄▌  ▄▄▄ . ▄▄▄·      ▄▄▄  ▄▄▄▄▄         ##
##    ▀▄ █·▐█ ▀█ •█▌▐███▪ ██ ▪     ·██ ▐███▪    •██  ▀▄.▀·██•  ▀▄.▀·▐█ ▄█▪     ▀▄ █·•██           ##
##    ▐▀▀▄ ▄█▀▀█ ▐█▐▐▌▐█· ▐█▌ ▄█▀▄ ▐█ ▌▐▌▐█·     ▐█.▪▐▀▀▪▄██▪  ▐▀▀▪▄ ██▀· ▄█▀▄ ▐▀▀▄  ▐█.▪         ##
##    ▐█•█▌▐█ ▪▐▌██▐█▌██. ██ ▐█▌.▐▌██ ██▌▐█▌     ▐█▌·▐█▄▄▌▐█▌▐▌▐█▄▄▌▐█▪·•▐█▌.▐▌▐█•█▌ ▐█▌·         ##
##    .▀  ▀ ▀  ▀ ▀▀ █▪▀▀▀▀▀•  ▀█▄▀▪▀▀  █▪▀▀▀     ▀▀▀  ▀▀▀ .▀▀▀  ▀▀▀ .▀    ▀█▄▀▪.▀  ▀ ▀▀▀          ##
####################################################################################################

### Hooks into the world border plugin to make sure the teleports stay within the boundry. http://dev.bukkit.org/bukkit-plugins/worldborder/
### Does not overide hard limits
## WorldBorderHook: true
### Not Yet Supported in public builds
###
  ### Does it cost to use Random Teleport?
cost: false
  ### If above is true, how much?
price: 20.0
  ### Asks the player if they want to teleport before teleporting them
askBeforeTeleporting: true
  ### Sets the hard border limit of how far Teleportation will go.
MaximumXRadius: 7000
MaximumXZadius: 7000
  ### If True will only teleport to pre set places.
HardSetTeleports: false
  ### Cooldown and Its Timer to reset.
Cooldown:
  ## amount of times it can be used before cooldowns activcate
  amount: 3
  ## Time it takes for a cooldown to activate
  time: 300
  ###
